name: Publish project to Maven repository
# Publish manually
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew build publish -PaquaticRepositoryUsername=${{ secrets.MAVEN_NAME }} -PaquaticRepositoryPassword=${{ secrets.MAVEN_SECRET }}
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token name
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)
          aquaticRepositoryUsername: ${{ secrets.MAVEN_NAME }}
          aquaticRepositoryPassword: ${{ secrets.MAVEN_SECRET }}
      - uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
              "id": "https://repo.nekroplex.com/",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
              "aquaticRepositoryUsername=${{ secrets.MAVEN_NAME }}"
              "aquaticRepositoryPassword=${{ secrets.MAVEN_SECRET }}"
            }]
